version: '3.7'
services:
  mongodb-secondary:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    environment:
      - MONGODB_REPLICA_SET_NAME=nam
      - MONGODB_ADVERTISED_HOSTNAME=172.31.85.231
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=172.31.92.249
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    network_mode: host
