version: '3.7'
services:
  mongodb-primary:
    image: bitnami/mongodb:4.4-debian-10
    environment:
      - MONGODB_REPLICA_SET_NAME=nam
      - MONGODB_ADVERTISED_HOSTNAME=172.31.92.249
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - ./mongodb_master_data:/bitnami/mongodb
    network_mode: host
